config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
 belongs_to :user
 has_many :article_categories
 has_many :categories, :through => :article_categories
 validates :title,
            presence: true,
            length: { minimum: 3, maximum: 50}
 validates :description,
            presence: true,
            length: { minimum: 10, maximum: 500}
 validates :user_id,
            presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, :through => :article_categories
    validates :name, presence: true, length: {minimum: 3, maximum: 25}
    validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles, dependent: :destroy
    before_save {self.email = email.downcase}

    validates :username, 
              presence: true,
              uniqueness: {case_sensitive: false},
              length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, 
              presence: true,
              uniqueness: {case_sensitive: false},
              format: {with: VALID_EMAIL_REGEX}

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   helper_method :current_user, :logged_in?

   def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
   end

   def logged_in?
    !!current_user
   end

   def require_user
    if !logged_in?
        flash[:danger] = "You must be login in to perform that action"
        redirect_to root_path
    end
   end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @articles = Article.all
    end
    
    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:success] = "Article was successfully created"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end

    def show  
    end

    def edit  
    end

    def update
        if @article.update(article_params)
            flash[:success] = "Article was successfully updated"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end

    def destroy
        @article.destroy
        flash[:danger] = "Article was successfully deleted"
        redirect_to articles_path
    end
   
    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
        if current_user != @article.user and !current_user.admin?
            flash[:danger] = "You can only edit or delete your own article"
            redirect_to root_path
        end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    before_action :require_admin, except: [:index, :show]

    def index
     @categories = Category.all
    end

    def new 
     @category = Category.new
    end

    def create
     @category = Category.new(category_params)
     if @category.save
        flash[:success] = 'Category was successfully created'
        redirect_to categories_path
     else
         render 'new'
     end
    end

    def edit
     @category = Category.find(params[:id])
    end

    def update
     @category = Category.find(params[:id])
     if @category.update(category_params)
        flash[:success] = 'Category name was successfully updated'
        redirect_to category_path(@category)
     else
        render 'edit'
     end
    end

    def show
     @category = Category.find(params[:id])
     @category_articles = @category.articles
    end

    private
    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !logged_in? || (logged_in? and !current_user.admin?)
          flash[:danger] = 'Only admin perform that action'
          redirect_to categories_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        redirect_to articles_path if logged_in?
    end

    def about
        
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You are succussfully login"
            redirect_to user_path(user)
        else
            flash.now[:danger] = "Wrong Credentials"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You are succussfully logout"
        redirect_to root_path
    end

    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:destroy]

    def index
       @users = User.all
    end

    def new
       @user = User.new 
    end

    def create
       @user = User.new(user_params)
       if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Welcome user #{@user.username}"
            redirect_to user_path(@user)
       else
            render 'new'
       end
    end

    def edit
    end

    def update
      if @user.update(user_params)
         flash[:success] = "Profile is updated"
         redirect_to articles_path
      else
         render 'edit'
      end
    end

    def show
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
      flash[:danger] = "User and article created by users have been deleted"
      redirect_to users_path
    end

    private
    
    def user_params
       params.require(:user).permit(:username, :email, :password)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_same_user
      if current_user != @user and !current_user.admin?
         flash[:danger] = "You can edit your own account"
         redirect_to root_path
      end
    end

    def require_admin
      if logged_in? and !current_user.admin?
         flash[:danger] = "Only admin can perform this action"
         redirect_to root_path
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url)
    end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>

<div class="card text-center">
  <div class="card-body">
    <h1 class="card-title"><%= link_to article.title, article_path(article) %></h1>
    <p class="card-text"><%= article.description %></p>
  </div>

  <% if article.categories.any? %>
   <p>Categories: <%= render article.categories %></p>
  <% end %>

  <% if logged_in? && (current_user == article.user || current_user.admin?) %>
  <div class="card-body border-top">
     <%= link_to "Edit", edit_article_path(article), class:"btn btn-dark" %>
     <%= link_to "Delete", article_path(article), method: :delete,
                                                  data: {confirm: 'Are you sure?'},
                                                  class:"btn btn-danger" %>
  </div>
  <% end %>
  <div class="card-footer text-muted">
    Created by: <%= article.user.username%> | 
    Created at: <%= time_ago_in_words(article.created_at) %> ago |
    Updated at: <%= time_ago_in_words(article.updated_at) %> ago 
  </div>
</div>

<div class="py-2"></div>

<% end %>

app/views/articles/_form.html.erb
<%= render "shared/alert", obj: @article %>

<%= form_with model: @article do |f| %>

  <div class="form-group">
     <%= f.label :title %>
     <%= f.text_field :title, class:"form-control", placeholder:"Title", autofocus: true %>
  </div>
  <div class="form-group">
     <%= f.label :description %>
     <%= f.text_field :description, class:"form-control", placeholder:"Description", autofocus: true %>
  </div>

  <div class="form form-group">
     <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
     <% cb.label(class: 'form-check form-check-inline') {cb.check_box(class: 'form-check-input') + cb.text} %>
     <% end %>
  </div>


  <div class="form-group">
    <%= f.submit "Submit", class:"btn btn-primary" %>
    <%= link_to "Back", root_path , class: "btn btn-dark"%>
  </div>

<% end %>

app/views/articles/edit.html.erb
<h1 class="center">Edit an Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="center">LISTING ALL ARTICLE</h1>

<div class="py-1"></div>

<%= render 'article', obj: @articles %> 

app/views/articles/new.html.erb
<h1 class="center">Create an Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="card text-center">
  <div class="card-header">Showing Selected Article</div>
  <div class="card-body">
    <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
    <h3 class="card-text"><%= link_to @article.user.username, user_path(@article.user) %></h3>
    <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
  </div>
  <hr class="my-1">
  <div class="card-body">
  
    <h1 class="card-title"><%= @article.title %></h1>
    <p class="card-text"><%= @article.description %></p>

    <% if @article.categories.any? %>
     <p>Categories: <%= render @article.categories %></p>
    <% end %>

    <% if logged_in? && (current_user == @article.user and current_user.admin?) %>
    <%= link_to "Edit", edit_article_path, class:"btn btn-primary" %>
    <% end %>

    <%= link_to "Back", articles_path, class: "btn btn-dark" %>

  </div>
  <div class="card-footer text-muted">
    Created by: <%= @article.user.username%> | 
    Created at: <%= time_ago_in_words(@article.created_at) %> ago |
    Updated at: <%= time_ago_in_words(@article.updated_at) %> ago
  </div>
</div>

app/views/categories/_category.html.erb
<span class='badge'><%= link_to category.name, category_path(category) %> </span>

app/views/categories/_form.html.erb
<%= render "shared/alert", obj: @category %>

<%= form_with model: @category do |f| %>

    <div class="form-group">
     <%= f.label :name %>
     <%= f.text_field :name, class:"form-control", placeholder:"Category name", autofocus: true %>
    </div>

    <div class="form-group">
    <%= f.submit class:"btn btn-primary" %>
    <%= link_to "Back", root_path , class: "btn btn-dark"%>
    </div>

<% end %>

app/views/categories/edit.html.erb
<h1 class="center">Edit Category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="center">Listing Categories</h1>

<% @categories.each do |category| %>

    <ul class="list-group">
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= link_to "#{category.name}", category_path(category)%>
        <span class="badge"><%= pluralize(category.articles.count, "article") %></span>
    </li>
    </ul>


<% end %>

app/views/categories/new.html.erb
<h1 class="center">Create New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="center"><%= "Category: " + @category.name %></h1>

<div class="py-1"></div>

<% if logged_in? and current_user.admin? %>
    <div class="center">
    <span class="badge"><%= link_to 'Edit Category Name', edit_category_path(@category) %></span>
    </div>
    <div class="py-1"></div>
<% end %>

<%= render 'articles/article', obj: @category_articles %> 

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
         Copyright &copy; <a href="https://faizanfsdev.netlify.app">Faizan's Portfolio</a> and have a look on <a href="https://github.com/FaizanFSDEV">GitHub Profile</a>
        </small>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %> alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= msg %>
   </div>
<% end %>


  

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class: "nav-link"%>
      </li>
      <li class="nav-item dropdown">

        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
             data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Category</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <a><%= link_to "All Categories", categories_path, class: "dropdown-item"%></a>
          <% Category.all.each do |category| %>
          <a><%= link_to "#{category.name}", category_path(category), class: "dropdown-item"%></a>
          <% end %>
          <% if logged_in? and current_user.admin? %>
          <div class="dropdown-divider"></div>
          <a><%= link_to "Create new category", new_category_path, class: "dropdown-item"%></a>
          <% end %>

        </div>
      </li>
      <% if logged_in? %>
                        <li class="nav-item">
                          <%= link_to "New Article", new_article_path, class: "nav-link"%>
                        </li>
                        <li class="nav-item">
                          <%= link_to "Users", users_path, class: "nav-link"%>
                        </li>
                        <li class="nav-item">
                          <%= link_to "Profile", user_path(current_user), class: "nav-link"%>
                        </li>
                        <li class="nav-item">
                        <% if current_user.admin? %>
                          <span class="badge badge-light">Admin</span>
                        <% end %>
                        </li>
                        <li class="nav-item">
                          <%= link_to "Edit Profile", edit_user_path(current_user), class: "nav-link"%>
                        </li>
                        <li class="nav-item">
                          <%= link_to "Logout", logout_path, method: :delete, class: "nav-link"%>
                        </li>
      <% else %>
                        <li class="nav-item">
                          <%= link_to "Signup", signup_path, class: "nav-link"%>
                        </li>
                        <li class="nav-item">
                          <%= link_to "Login", login_path, class: "nav-link"%>
                        </li>      
      <% end %>
    </ul>
    
    <form class="form-inline my-2 my-lg-0">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>

  </div>
</nav>





    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alphablog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navigation' %>
    

    <div class="container">
      <br>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
    
    <br>
    <br>
    <div class="container alert-info py-2" role="alert">
      <%= debug(params) if Rails.env.development? %>
    </div>
    
  </body>
</html>

app/views/pages/about.html.erb
<div class="center jumbotron">
  <h1 class="display-4">About Page</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1 class="display-4">Home Page</h1>
  <p class="lead">This is a simple hero unit.</p>
  <hr class="my-4">
  <p>Sign up to discover new world of RUBY</p>
  <%= link_to "Sign Up", signup_path, class: "btn btn-danger btn-lg btn-xlarge" %>
</div>

app/views/shared/_alert.html.erb
<% if obj.errors.any? %>

<div class="alert alert-danger" role="alert">


    <h2>
    <% if obj = @article %>
    <%= pluralize(obj.errors.count,'error')%> prohibited article from being saved
    <% elsif obj = @category %>
    <%= pluralize(obj.errors.count,'error')%> prohibited category from being saved
    <% else obj = @user %>
    <%= pluralize(obj.errors.count,'error')%> prohibited user from being signup
    <% end %>
    </h2>
    <ul class="alert-link">
        <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>


</div>

<% end %>

app/views/users/_form.html.erb
<%= form_with model: @user do |f| %>

    <div class="form-group">
     <%= f.label :username %>
     <%= f.text_field :username, class:"form-control", placeholder:"Username", autofocus: true %>
    </div>

    <div class="form-group">
     <%= f.label :email %>
     <%= f.text_field :email, class:"form-control", placeholder:"Email", autofocus: true %>
    </div>

    <div class="form-group">
     <%= f.label :password %>
     <%= f.text_field :password, class:"form-control", placeholder:"Password", autofocus: true %>
    </div>

    <div class="form-group">
    <%= f.submit(@user.new_record? ? "Sign Up" : "Update", class:"btn btn-primary") %>
    <%= link_to "Back", root_path , class: "btn btn-dark"%>
    </div>

<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render "shared/alert", obj: @user %>

<%= render "form" %>

app/views/users/index.html.erb
<h1 class="center">All Blogger</h1>

<hr class="my-4">

<% @users.each do |user| %>

<div class="card text-center">
  <div class="card-header">
    <%= link_to gravatar_for(user), user_path(user) %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= link_to user.username, user_path(user) %></h5>
    <p class="card-text"><%= pluralize(user.articles.count, "article") if user.articles %></p>
    <% if logged_in? and current_user.admin? %>
    <p> <%= link_to "Delete this user", user_path(user), method: :delete, 
                                                         data: {confirm: "Are you sure?"}%>
    </p>
    <% end %>
  </div>
</div>
<div class="py-2"></div>


<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "shared/alert", obj: @user %>

<%= render "form" %>

app/views/users/show.html.erb
<h1 class="center">Welcome <%= @user.username %></h1>

<h2 class="center"><%= gravatar_for @user %></h2>

<h3 class="center"><%= @user.username %>'s article</h3>

<%= render 'articles/article', obj: @user.articles %>